services:
  web:
    build: ./api
    ports:
      - "5000:5000"
    volumes:
      - ./api:/app
    depends_on:
      - db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_URL: jdbc:postgresql://db:5432/master
      HS256_SECRET: secret
  db:
    image: postgres:12
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data 
    environment:
      POSTGRES_DB: master
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
volumes:
  postgres_data: